**Author:** Rossana Ramirez 

**Linkedin:** rossana-ramirez-villegas-527532192/

**date:** 2024-09-20


In [3]:
import os
import pandas as pd
import numpy as np

***1. pandas version***

What's the version of Pandas that you installed?

In [4]:
print(f"The version of pandas is: {pd.__version__}")

The version of pandas is: 2.2.2


***Getting the data***


In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [6]:
df.head(2)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

***2. Records count***

How many records are in the dataset?

In [7]:
print(f"The number records in the dataset is: {df.shape[0]}")

The number records in the dataset is: 2160


***Q3. Laptop brands***

How many laptop brands are presented in the dataset?

In [8]:
print(f"There are {len(df.Brand.unique())} laptop brands")

There are 27 laptop brands


***Q4. Missing values***

How many columns in the dataset have missing values?

In [9]:
print(f"The columns with missing values are: {df.isnull().any().sum()}")

The columns with missing values are: 3


***Q5. Maximum final price***

What's the maximum final price of Dell notebooks in the dataset?

In [10]:
print(f"Dell brand max price is: {df[df.Brand == 'Dell']['Final Price'].max()}")

Dell brand max price is: 3936.0


***Q6. Median value of Screen***


- 6.1 Find the median value of Screen column in the dataset.


In [11]:
print(f"The medain value is: {df.Screen.median()}")

The medain value is: 15.6


- 6.2 Next, calculate the most frequent value of the same Screen column.

In [12]:
print(f"Most frequent screen column value is: {df.Screen.mode()[0]}")

Most frequent screen column value is: 15.6


- 6.3 Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [13]:
df['Screen'] = df['Screen'].fillna(df.Screen.mode()[0])

- 6.4 Now, calculate the median value of Screen once again.

In [14]:
print(f"median after filling the missing values: {df.Screen.median()}")

median after filling the missing values: 15.6


***Has it changed?***
- No.

***Q7. Sum of weights***

***Note:*** You just implemented linear regression. We'll talk about it in the next lesson.

- 7.1 Select all the "Innjoo" laptops from the dataset.

In [15]:
brand_innjoo = df[df.Brand == 'Innjoo']
brand_innjoo.shape

(6, 12)

- 7.2 Select only columns RAM, Storage, Screen.

In [16]:
brand_innjoo_filtered = brand_innjoo[['RAM', 'Storage', 'Screen']]
brand_innjoo_filtered.head()

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1

- 7.3 Get the underlying NumPy array. Let's call it X.

In [17]:
X = brand_innjoo_filtered.to_numpy()
print(X)


[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


- 7.4 Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [18]:
XTX = np.dot(X.T, X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


- 7.5 Compute the inverse of XTX.

In [19]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


- 7.6 Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

- 7.7 Multiply the inverse of XTX witxh the transpose of X, and then multiply the result by y. Call the result w.

In [21]:
XTX_inv_XT = np.dot(XTX_inv, X.T)
print(XTX_inv_XT)

[[ 0.26298349 -0.12560233 -0.40646389  0.14958687  0.05244042  0.05244042]
 [-0.00110155  0.00295059  0.00125892 -0.00177691 -0.00076387 -0.00076387]
 [-0.08772226  0.0269791   0.17140891 -0.0302108  -0.00153546 -0.00153546]]


In [22]:
w = np.dot(XTX_inv_XT, y)
print(w)

[45.58076606  0.42783519 45.29127938]


- 7.8 What's the sum of all the elements of the result?

In [23]:
sum_w = sum(w)
print(sum_w)

91.29988062995753
